In [1]:
!rm -rf output-*/

## Test 1: discretize = True, use_ordinal_encoding = False

In [2]:
!mkdir -p output-1-parallel

In [3]:
! PYTHONPATH="$PYTHONPATH:../../" \
python -m FIDDLE.run \
    --data_fname='./input/data.csv' \
    --population_fname='./input/pop.csv' \
    --config_fname='./input/config-1-parallel.yaml' \
    --output_dir='./output-1-parallel/' \
    --T=4 --dt=1.0 \
    --theta_1=0.001 --theta_2=0.001 --theta_freq=1 \
    --stats_functions 'min' 'max' 'mean'

Input:
    Data      : ./input/data.csv
    Population: ./input/pop.csv
    Config    : ./input/config-1-parallel.yaml

Output directory: ./output-1-parallel/

Input arguments:
    T      = 4.0
    dt     = 1.0
    θ₁     = 0.001
    θ₂     = 0.001
    θ_freq = 1.0
    k      = 3 ['min', 'max', 'mean']

discretize = yes
    S discretization bins: to be computed from data
    X discretization bins: to be computed from data

N = 200
L = 4


================================================================================
1) Pre-filter
================================================================================
Remove rows not in population
Remove rows with t outside of [0, 4]
Remove rare variables (<= 0.001)
Total variables     : 1970
Rare variables      : 0
Remaining variables : 1970
# rows (original)   : 64777
# rows (filtered)   : 64777

================================================================================
2) Transform; 3) Post-filter
================================================================================

--------------------------------------------------------------------------------
*) Detecting and parsing value types
--------------------------------------------------------------------------------
Saved as: ./output-1-parallel/value_types.csv

--------------------------------------------------------------------------------
*) Separate time-invariant and time-dependent
--------------------------------------------------------------------------------
Variables (time-invariant): 12
Variables (time-dependent): 1958
# rows    (time-invariant): 2400
# rows    (time-dependent): 62377

--------------------------------------------------------------------------------
2-A) Transform time-invariant data
--------------------------------------------------------------------------------
(N × ^d) table            :	 (200, 12)
number of missing entries :	 4 out of 2400 total
Time elapsed: 0.018219 seconds

Output
S_all, binary features    :	 (200, 84)
Time elapsed: 0.202440 seconds

--------------------------------------------------------------------------------
3-A) Post-filter time-invariant data
--------------------------------------------------------------------------------
Original       : 84
Nearly-constant: 0
Correlated     : 7
Time elapsed: 0.208578 seconds

Output
S: shape=(200, 77), density=0.145
Total time: 0.211770 seconds


--------------------------------------------------------------------------------
2-B) Transform time-dependent data
--------------------------------------------------------------------------------
Total variables    : 1958
Frequent variables : ['DiaBP', 'HR', 'RR', 'SpO2', 'SysBP']
M₁ = 5
M₂ = 1953
k  = 3 ['min', 'max', 'mean']

Transforming each example...
Batches of size 100:  2
100%|█████████████████████████████████████████████| 2/2 [00:25<00:00, 12.88s/it]

Parallel processing done
DONE: Transforming each example...
(freq) number of missing entries :	 996 out of 200×4×5=4000 total
(freq) number of imputed entries :	 58
(freq) number of not imputed entries :	 938
(non-freq) number of missing entries :	 1510389 out of 200×4×1953=1562400 total

(N × L × ^D) table :	 (200, 4, 1983)
Time elapsed: 27.030075 seconds
Discretizing features...

Processing 1978 non-boolean variable columns...
    Computing bin edges for numeric variables...
100%|██████████████████████████████████████| 1978/1978 [00:04<00:00, 399.11it/s]
    Discretizing variables to binary features
100%|██████████████████████████████████████| 1978/1978 [00:10<00:00, 193.81it/s]
Finished discretizing features

Output
X_all: shape=(200, 4, 3582), density=0.025
Time elapsed: 43.360937 seconds

--------------------------------------------------------------------------------
3-B) Post-filter time-dependent data
--------------------------------------------------------------------------------
(200, 4, 3582) 0.024868439419318815
Original : 3582
Nearly-constant: 77
*** time:  5.742851972579956
Correlated     : 1144
*** time:  10.776153087615967

Output
X: shape=(200, 4, 2361), density=0.034
(200, 4, 2361) 0.034196844557390936
Time elapsed: 54.146272 seconds

Output
X: shape=(200, 4, 2361), density=0.034
Total time: 54.197789 seconds

In [4]:
import numpy as np
import pandas as pd
import json
import sparse

S = sparse.load_npz('output-1-parallel/S_all.npz')
S_names = json.load(open('output-1-parallel/S_all.feature_names.json', 'r'))
S_index = pd.read_csv('output-1-parallel/S.ID.csv').set_index(['ID'])
df_S = pd.DataFrame(S.todense(), columns=S_names, index=S_index.index)

X = sparse.load_npz('output-1-parallel/X_all.npz')
X_names = json.load(open('output-1-parallel/X_all.feature_names.json', 'r'))
X_index = pd.read_csv('output-1-parallel/X.ID,t_range.csv').set_index(['ID', 't_range'])
df_X = pd.DataFrame(X.todense().reshape(-1, X.shape[-1]), columns=X_names, index=X_index.index)

display(df_S)
display(df_X)

,ADMISSION_LOCATION_value_CLINIC REFERRAL/PREMATURE,ADMISSION_LOCATION_value_EMERGENCY ROOM ADMIT,ADMISSION_LOCATION_value_PHYS REFERRAL/NORMAL DELI,ADMISSION_LOCATION_value_TRANSFER FROM HOSP/EXTRAM,ADMISSION_LOCATION_value_TRANSFER FROM OTHER HEALT,ADMISSION_LOCATION_value_TRANSFER FROM SKILLED NUR,ADMISSION_TYPE_value_ELECTIVE,ADMISSION_TYPE_value_EMERGENCY,ADMISSION_TYPE_value_URGENT,"AGE_value_(19.737, 50.02]",...,RELIGION_value_EPISCOPALIAN,RELIGION_value_GREEK ORTHODOX,RELIGION_value_JEHOVAH'S WITNESS,RELIGION_value_JEWISH,RELIGION_value_MUSLIM,RELIGION_value_NOT SPECIFIED,RELIGION_value_OTHER,RELIGION_value_PROTESTANT QUAKER,RELIGION_value_UNITARIAN-UNIVERSALIST,RELIGION_value_UNOBTAINABLE
ID,,,,,,,,,,,,,,,,,,,,,
200001,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
200010,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0
200016,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
200033,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
200034,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201110,1,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,0
201113,0,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
201124,0,0,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
201125,1,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,0,0,0
201128,0,0,0,1,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

                   DiaBP_mask  HR_mask  RR_mask  SpO2_mask  SysBP_mask  \
ID     t_range
200001 [0.0, 1.0)           1        1        1          1           1
       [1.0, 2.0)           1        1        1          1           1
       [2.0, 3.0)           1        1        1          1           1
       [3.0, 4.0)           1        1        1          1           1
200010 [0.0, 1.0)           0        0        0          0           0
...                       ...      ...      ...        ...         ...
201125 [3.0, 4.0)           1        1        1          1           1
201128 [0.0, 1.0)           0        0        0          0           0
       [1.0, 2.0)           1        1        1          0           1
       [2.0, 3.0)           1        1        1          0           1
       [3.0, 4.0)           1        1        1          0           1

                   220046_value_(9.999, 120.0]  220046_value_(120.0, 200.0]  \
ID     t_range
200001 [0.0, 1.0)                            1                            0
       [1.0, 2.0)                            0                            0
       [2.0, 3.0)                            0                            0
       [3.0, 4.0)                            0                            0
200010 [0.0, 1.0)                            1                            0
...                                        ...                          ...
201125 [3.0, 4.0)                            0                            1
201128 [0.0, 1.0)                            0                            0
       [1.0, 2.0)                            1                            0
       [2.0, 3.0)                            0                            0
       [3.0, 4.0)                            0                            0

                   220047_value_(28.999, 50.0]  220047_value_(50.0, 55.0]  \
ID     t_range
200001 [0.0, 1.0)                            0                          0
       [1.0, 2.0)                            0                          0
       [2.0, 3.0)                            0                          0
       [3.0, 4.0)                            0                          0
200010 [0.0, 1.0)                            1                          0
...                                        ...                        ...
201125 [3.0, 4.0)                            0                          0
201128 [0.0, 1.0)                            0                          0
       [1.0, 2.0)                            1                          0
       [2.0, 3.0)                            0                          0
       [3.0, 4.0)                            0                          0

                   220047_value_(55.0, 60.0]  ...  SysBP_max_(65.999, 105.0]  \
ID     t_range                                ...
200001 [0.0, 1.0)                          1  ...                          0
       [1.0, 2.0)                          0  ...                          0
       [2.0, 3.0)                          0  ...                          0
       [3.0, 4.0)                          0  ...                          1
200010 [0.0, 1.0)                          0  ...                          0
...                                      ...  ...                        ...
201125 [3.0, 4.0)                          1  ...                          0
201128 [0.0, 1.0)                          0  ...                          0
       [1.0, 2.0)                          0  ...                          0
       [2.0, 3.0)                          0  ...                          0
       [3.0, 4.0)                          0  ...                          0

                   SysBP_max_(105.0, 116.0]  SysBP_max_(116.0, 127.0]  \
ID     t_range
200001 [0.0, 1.0)                         1                         0
       [1.0, 2.0)                         1                         0
       [2.0, 3.0)                         1                         0
       [3.0, 4.0)                         0                         0
200010 [0.0, 1.0)                         0                         0
...                                     ...                       ...
201125 [3.0, 4.0)                         0                         1
201128 [0.0, 1.0)                         0                         0
       [1.0, 2.0)                         0                         0
       [2.0, 3.0)                         0                         1
       [3.0, 4.0)                         0                         1

                   SysBP_max_(127.0, 141.0]  SysBP_max_(141.0, 214.0]  \
ID     t_range
200001 [0.0, 1.0)                         0                         0
       [1.0, 2.0)                         0                         0
       [2.0, 3.0)                         0                         0
       [3.0, 4.0)                         0                         0
200010 [0.0, 1.0)                         0                         0
...                                     ...                       ...
201125 [3.0, 4.0)                         0                         0
201128 [0.0, 1.0)                         0                         0
       [1.0, 2.0)                         1                         0
       [2.0, 3.0)                         0                         0
       [3.0, 4.0)                         0                         0

                   SysBP_mean_(65.999, 103.4]  SysBP_mean_(103.4, 114.433]  \
ID     t_range
200001 [0.0, 1.0)                           0                            1
       [1.0, 2.0)                           0                            1
       [2.0, 3.0)                           0                            0
       [3.0, 4.0)                           1                            0
200010 [0.0, 1.0)                           0                            0
...                                       ...                          ...
201125 [3.0, 4.0)                           0                            0
201128 [0.0, 1.0)                           0                            0
       [1.0, 2.0)                           0                            0
       [2.0, 3.0)                           0                            0
       [3.0, 4.0)                           0                            0

                   SysBP_mean_(114.433, 125.0]  SysBP_mean_(125.0, 138.0]  \
ID     t_range
200001 [0.0, 1.0)                            0                          0
       [1.0, 2.0)                            0                          0
       [2.0, 3.0)                            1                          0
       [3.0, 4.0)                            0                          0
200010 [0.0, 1.0)                            0                          0
...                                        ...                        ...
201125 [3.0, 4.0)                            1                          0
201128 [0.0, 1.0)                            0                          0
       [1.0, 2.0)                            0                          1
       [2.0, 3.0)                            1                          0
       [3.0, 4.0)                            1                          0

                   SysBP_mean_(138.0, 206.0]
ID     t_range
200001 [0.0, 1.0)                          0
       [1.0, 2.0)                          0
       [2.0, 3.0)                          0
       [3.0, 4.0)                          0
200010 [0.0, 1.0)                          0
...                                      ...
201125 [3.0, 4.0)                          0
201128 [0.0, 1.0)                          0
       [1.0, 2.0)                          0
       [2.0, 3.0)                          0
       [3.0, 4.0)                          0

[800 rows x 3582 columns]

## Test 2: discretize = True, use_ordinal_encoding = True

In [1]:
!mkdir -p output-2-parallel

In [2]:
! PYTHONPATH="$PYTHONPATH:../../" \
python -m FIDDLE.run \
    --data_fname='./input/data.csv' \
    --population_fname='./input/pop.csv' \
    --config_fname='./input/config-2-parallel.yaml' \
    --output_dir='./output-2-parallel/' \
    --T=4 --dt=1.0 \
    --theta_1=0.001 --theta_2=0.001 --theta_freq=1 \
    --stats_functions 'min' 'max' 'mean'

Input:
    Data      : ./input/data.csv
    Population: ./input/pop.csv
    Config    : ./input/config-2-parallel.yaml

Output directory: ./output-2-parallel/

Input arguments:
    T      = 4.0
    dt     = 1.0
    θ₁     = 0.001
    θ₂     = 0.001
    θ_freq = 1.0
    k      = 3 ['min', 'max', 'mean']

discretize = yes
    S discretization bins: to be computed from data
    X discretization bins: to be computed from data

N = 200
L = 4


================================================================================
1) Pre-filter
================================================================================
Remove rows not in population
Remove rows with t outside of [0, 4]
Remove rare variables (<= 0.001)
Total variables     : 1970
Rare variables      : 0
Remaining variables : 1970
# rows (original)   : 64777
# rows (filtered)   : 64777

================================================================================
2) Transform; 3) Post-filter
================================================================================

--------------------------------------------------------------------------------
*) Detecting and parsing value types
--------------------------------------------------------------------------------
Saved as: ./output-2-parallel/value_types.csv

--------------------------------------------------------------------------------
*) Separate time-invariant and time-dependent
--------------------------------------------------------------------------------
Variables (time-invariant): 12
Variables (time-dependent): 1958
# rows    (time-invariant): 2400
# rows    (time-dependent): 62377

--------------------------------------------------------------------------------
2-A) Transform time-invariant data
--------------------------------------------------------------------------------
(N × ^d) table            :	 (200, 12)
number of missing entries :	 4 out of 2400 total
Time elapsed: 0.016319 seconds

Output
S_all, binary features    :	 (200, 84)
Time elapsed: 0.277533 seconds

--------------------------------------------------------------------------------
3-A) Post-filter time-invariant data
--------------------------------------------------------------------------------
Original       : 84
Nearly-constant: 0
Correlated     : 8
Time elapsed: 0.287127 seconds

Output
S: shape=(200, 76), density=0.200
Total time: 0.291958 seconds


--------------------------------------------------------------------------------
2-B) Transform time-dependent data
--------------------------------------------------------------------------------
Total variables    : 1958
Frequent variables : ['DiaBP', 'HR', 'RR', 'SpO2', 'SysBP']
M₁ = 5
M₂ = 1953
k  = 3 ['min', 'max', 'mean']

Transforming each example...
Batches of size 100:  2
100%|█████████████████████████████████████████████| 2/2 [00:24<00:00, 12.47s/it]

Parallel processing done
DONE: Transforming each example...
(freq) number of missing entries :	 996 out of 200×4×5=4000 total
(freq) number of imputed entries :	 58
(freq) number of not imputed entries :	 938
(non-freq) number of missing entries :	 1510389 out of 200×4×1953=1562400 total

(N × L × ^D) table :	 (200, 4, 1983)
Time elapsed: 26.302975 seconds
Discretizing features...

Processing 1978 non-boolean variable columns...
    Computing bin edges for numeric variables...
100%|██████████████████████████████████████| 1978/1978 [00:04<00:00, 399.19it/s]
    Discretizing variables to binary features
100%|██████████████████████████████████████| 1978/1978 [00:09<00:00, 208.45it/s]
Finished discretizing features

Output
X_all: shape=(200, 4, 3587), density=0.036
Time elapsed: 41.840676 seconds

--------------------------------------------------------------------------------
3-B) Post-filter time-dependent data
--------------------------------------------------------------------------------
(200, 4, 3587) 0.036313771954279345
Original : 3587
Nearly-constant: 0
*** time:  5.449969053268433
Correlated     : 1173
*** time:  10.53041410446167

Output
X: shape=(200, 4, 2414), density=0.049
(200, 4, 2414) 0.048544946147473074
Time elapsed: 52.379346 seconds

Output
X: shape=(200, 4, 2414), density=0.049
Total time: 52.431078 seconds

In [3]:
import numpy as np
import pandas as pd
import json
import sparse

S = sparse.load_npz('output-2-parallel/S_all.npz')
S_names = json.load(open('output-2-parallel/S_all.feature_names.json', 'r'))
S_index = pd.read_csv('output-2-parallel/S.ID.csv').set_index(['ID'])
df_S = pd.DataFrame(S.todense(), columns=S_names, index=S_index.index)

X = sparse.load_npz('output-2-parallel/X_all.npz')
X_names = json.load(open('output-2-parallel/X_all.feature_names.json', 'r'))
X_index = pd.read_csv('output-2-parallel/X.ID,t_range.csv').set_index(['ID', 't_range'])
df_X = pd.DataFrame(X.todense().reshape(-1, X.shape[-1]), columns=X_names, index=X_index.index)

display(df_S)
display(df_X)

,ADMISSION_LOCATION_value_CLINIC REFERRAL/PREMATURE,ADMISSION_LOCATION_value_EMERGENCY ROOM ADMIT,ADMISSION_LOCATION_value_PHYS REFERRAL/NORMAL DELI,ADMISSION_LOCATION_value_TRANSFER FROM HOSP/EXTRAM,ADMISSION_LOCATION_value_TRANSFER FROM OTHER HEALT,ADMISSION_LOCATION_value_TRANSFER FROM SKILLED NUR,ADMISSION_TYPE_value_ELECTIVE,ADMISSION_TYPE_value_EMERGENCY,ADMISSION_TYPE_value_URGENT,AGE_value>19.737885622780315,...,RELIGION_value_EPISCOPALIAN,RELIGION_value_GREEK ORTHODOX,RELIGION_value_JEHOVAH'S WITNESS,RELIGION_value_JEWISH,RELIGION_value_MUSLIM,RELIGION_value_NOT SPECIFIED,RELIGION_value_OTHER,RELIGION_value_PROTESTANT QUAKER,RELIGION_value_UNITARIAN-UNIVERSALIST,RELIGION_value_UNOBTAINABLE
ID,,,,,,,,,,,,,,,,,,,,,
200001,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,1,0,0,0,0,0
200010,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0
200016,0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,0
200033,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
200034,0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201110,1,0,0,0,0,0,0,1,0,1,...,0,0,0,0,0,1,0,0,0,0
201113,0,1,0,0,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
201124,0,0,1,0,0,0,1,0,0,1,...,0,0,0,0,0,1,0,0,0,0
201125,1,0,0,0,0,0,0,1,0,1,...,0,0,0,1,0,0,0,0,0,0
201128,0,0,0,1,0,0,0,1,0,1,...,0,0,0,0,0,0,0,0,0,0

                   DiaBP_mask  HR_mask  RR_mask  SpO2_mask  SysBP_mask  \
ID     t_range
200001 [0.0, 1.0)           1        1        1          1           1
       [1.0, 2.0)           1        1        1          1           1
       [2.0, 3.0)           1        1        1          1           1
       [3.0, 4.0)           1        1        1          1           1
200010 [0.0, 1.0)           0        0        0          0           0
...                       ...      ...      ...        ...         ...
201125 [3.0, 4.0)           1        1        1          1           1
201128 [0.0, 1.0)           0        0        0          0           0
       [1.0, 2.0)           1        1        1          0           1
       [2.0, 3.0)           1        1        1          0           1
       [3.0, 4.0)           1        1        1          0           1

                   220046_value>10.0  220046_value>120.0  220047_value>29.0  \
ID     t_range
200001 [0.0, 1.0)                  1                   0                  1
       [1.0, 2.0)                  0                   0                  0
       [2.0, 3.0)                  0                   0                  0
       [3.0, 4.0)                  0                   0                  0
200010 [0.0, 1.0)                  1                   0                  1
...                              ...                 ...                ...
201125 [3.0, 4.0)                  1                   1                  1
201128 [0.0, 1.0)                  0                   0                  0
       [1.0, 2.0)                  1                   0                  1
       [2.0, 3.0)                  0                   0                  0
       [3.0, 4.0)                  0                   0                  0

                   220047_value>50.0  220047_value>55.0  ...  SysBP_mean>66.0  \
ID     t_range                                           ...
200001 [0.0, 1.0)                  1                  1  ...                1
       [1.0, 2.0)                  0                  0  ...                1
       [2.0, 3.0)                  0                  0  ...                1
       [3.0, 4.0)                  0                  0  ...                1
200010 [0.0, 1.0)                  0                  0  ...                0
...                              ...                ...  ...              ...
201125 [3.0, 4.0)                  1                  1  ...                1
201128 [0.0, 1.0)                  0                  0  ...                0
       [1.0, 2.0)                  0                  0  ...                1
       [2.0, 3.0)                  0                  0  ...                1
       [3.0, 4.0)                  0                  0  ...                1

                   SysBP_mean>103.4  SysBP_mean>114.43333333333334  \
ID     t_range
200001 [0.0, 1.0)                 1                              0
       [1.0, 2.0)                 1                              0
       [2.0, 3.0)                 1                              1
       [3.0, 4.0)                 0                              0
200010 [0.0, 1.0)                 0                              0
...                             ...                            ...
201125 [3.0, 4.0)                 1                              1
201128 [0.0, 1.0)                 0                              0
       [1.0, 2.0)                 1                              1
       [2.0, 3.0)                 1                              1
       [3.0, 4.0)                 1                              1

                   SysBP_mean>125.0  SysBP_mean>138.0  SysBP_max>66.0  \
ID     t_range
200001 [0.0, 1.0)                 0                 0               1
       [1.0, 2.0)                 0                 0               1
       [2.0, 3.0)                 0                 0               1
       [3.0, 4.0)                 0                 0               1
200010 [0.0, 1.0)                 0                 0               0
...                             ...               ...             ...
201125 [3.0, 4.0)                 0                 0               1
201128 [0.0, 1.0)                 0                 0               0
       [1.0, 2.0)                 1                 0               1
       [2.0, 3.0)                 0                 0               1
       [3.0, 4.0)                 0                 0               1

                   SysBP_max>105.0  SysBP_max>116.0  SysBP_max>127.0  \
ID     t_range
200001 [0.0, 1.0)                1                0                0
       [1.0, 2.0)                1                0                0
       [2.0, 3.0)                1                0                0
       [3.0, 4.0)                0                0                0
200010 [0.0, 1.0)                0                0                0
...                            ...              ...              ...
201125 [3.0, 4.0)                1                1                0
201128 [0.0, 1.0)                0                0                0
       [1.0, 2.0)                1                1                1
       [2.0, 3.0)                1                1                0
       [3.0, 4.0)                1                1                0

                   SysBP_max>141.0
ID     t_range
200001 [0.0, 1.0)                0
       [1.0, 2.0)                0
       [2.0, 3.0)                0
       [3.0, 4.0)                0
200010 [0.0, 1.0)                0
...                            ...
201125 [3.0, 4.0)                0
201128 [0.0, 1.0)                0
       [1.0, 2.0)                0
       [2.0, 3.0)                0
       [3.0, 4.0)                0

[800 rows x 3587 columns]

## Test 3: discretize = False

In [8]:
!mkdir -p output-3-parallel

In [9]:
! PYTHONPATH="$PYTHONPATH:../../" \
python -m FIDDLE.run \
    --data_fname='./input/data.csv' \
    --population_fname='./input/pop.csv' \
    --config_fname='./input/config-3-parallel.yaml' \
    --output_dir='./output-3-parallel/' \
    --T=4 --dt=1.0 \
    --theta_1=0.001 --theta_2=0.001 --theta_freq=1 \
    --stats_functions 'min' 'max' 'mean'

Input:
    Data      : ./input/data.csv
    Population: ./input/pop.csv
    Config    : ./input/config-3-parallel.yaml

Output directory: ./output-3-parallel/

Input arguments:
    T      = 4.0
    dt     = 1.0
    θ₁     = 0.001
    θ₂     = 0.001
    θ_freq = 1.0
    k      = 3 ['min', 'max', 'mean']

discretize = no

N = 200
L = 4


================================================================================
1) Pre-filter
================================================================================
Remove rows not in population
Remove rows with t outside of [0, 4]
Remove rare variables (<= 0.001)
Total variables     : 1970
Rare variables      : 0
Remaining variables : 1970
# rows (original)   : 64777
# rows (filtered)   : 64777

================================================================================
2) Transform; 3) Post-filter
================================================================================

--------------------------------------------------------------------------------
*) Detecting and parsing value types
--------------------------------------------------------------------------------
Saved as: ./output-3-parallel/value_types.csv

--------------------------------------------------------------------------------
*) Separate time-invariant and time-dependent
--------------------------------------------------------------------------------
Variables (time-invariant): 12
Variables (time-dependent): 1958
# rows    (time-invariant): 2400
# rows    (time-dependent): 62377

--------------------------------------------------------------------------------
2-A) Transform time-invariant data
--------------------------------------------------------------------------------
(N × ^d) table            :	 (200, 12)
number of missing entries :	 4 out of 2400 total
Time elapsed: 0.011708 seconds

Output
S_all, binary features    :	 (200, 76)
Time elapsed: 0.123038 seconds

--------------------------------------------------------------------------------
3-A) Post-filter time-invariant data
--------------------------------------------------------------------------------
Original       : 76
Nearly-constant: 0
Correlated     : 7
Time elapsed: 0.126716 seconds

Output
S: shape=(200, 69), density=0.162
Total time: 0.129411 seconds


--------------------------------------------------------------------------------
2-B) Transform time-dependent data
--------------------------------------------------------------------------------
Total variables    : 1958
Frequent variables : ['DiaBP', 'HR', 'RR', 'SpO2', 'SysBP']
M₁ = 5
M₂ = 1953
k  = 3 ['min', 'max', 'mean']

Transforming each example...
Batches of size 100:  2
100%|█████████████████████████████████████████████| 2/2 [00:23<00:00, 11.65s/it]

Parallel processing done
DONE: Transforming each example...
(freq) number of missing entries :	 996 out of 200×4×5=4000 total
(freq) number of imputed entries :	 58
(freq) number of not imputed entries :	 938
(non-freq) number of missing entries :	 1510389 out of 200×4×1953=1562400 total

(N × L × ^D) table :	 (200, 4, 1983)
Time elapsed: 24.511847 seconds
Discretizing features...

Discretizing categorical features...
100%|██████████████████████████████████████| 1990/1990 [00:07<00:00, 266.00it/s]
Finished discretizing features

Output
X_all: shape=(200, 4, 2588), density=0.582
Time elapsed: 34.279819 seconds

--------------------------------------------------------------------------------
3-B) Post-filter time-dependent data
--------------------------------------------------------------------------------
(200, 4, 2588) 0.5818387751159196
Original : 2588
Nearly-constant: 1064
*** time:  5.1737799644470215
/Users/shengputang/Developer/FIDDLE/FIDDLE/helpers.py:426: RuntimeWarning: invalid value encountered in sqrt
  coeffs = C / np.sqrt(np.outer(d, d))
/Users/shengputang/Developer/FIDDLE/FIDDLE/helpers.py:426: RuntimeWarning: divide by zero encountered in true_divide
  coeffs = C / np.sqrt(np.outer(d, d))
/Users/shengputang/Developer/FIDDLE/FIDDLE/helpers.py:426: RuntimeWarning: invalid value encountered in true_divide
  coeffs = C / np.sqrt(np.outer(d, d))
/Users/shengputang/Developer/FIDDLE/FIDDLE/helpers.py:376: RuntimeWarning: invalid value encountered in multiply
  self.corr_matrix *= np.tri(*self.corr_matrix.shape)
Correlated     : 310
*** time:  8.826726913452148

Output
X: shape=(200, 4, 1214), density=0.366
(200, 4, 1214) 0.366085255354201
Time elapsed: 43.112199 seconds

Output
X: shape=(200, 4, 1214), density=0.366
Total time: 43.318430 seconds

In [10]:
import numpy as np
import pandas as pd
import json
import sparse

S = sparse.load_npz('output-3-parallel/S_all.npz')
S_names = json.load(open('output-3-parallel/S_all.feature_names.json', 'r'))
S_index = pd.read_csv('output-3-parallel/S.ID.csv').set_index(['ID'])
df_S = pd.DataFrame(S.todense(), columns=S_names, index=S_index.index)

X = sparse.load_npz('output-3-parallel/X_all.npz')
X_names = json.load(open('output-3-parallel/X_all.feature_names.json', 'r'))
X_index = pd.read_csv('output-3-parallel/X.ID,t_range.csv').set_index(['ID', 't_range'])
df_X = pd.DataFrame(X.todense().reshape(-1, X.shape[-1]), columns=X_names, index=X_index.index)

display(df_S)
display(df_X)

,ADMISSION_LOCATION_value:CLINIC REFERRAL/PREMATURE,ADMISSION_LOCATION_value:EMERGENCY ROOM ADMIT,ADMISSION_LOCATION_value:PHYS REFERRAL/NORMAL DELI,ADMISSION_LOCATION_value:TRANSFER FROM HOSP/EXTRAM,ADMISSION_LOCATION_value:TRANSFER FROM OTHER HEALT,ADMISSION_LOCATION_value:TRANSFER FROM SKILLED NUR,ADMISSION_TYPE_value:ELECTIVE,ADMISSION_TYPE_value:EMERGENCY,ADMISSION_TYPE_value:URGENT,AGE_value,...,RELIGION_value:EPISCOPALIAN,RELIGION_value:GREEK ORTHODOX,RELIGION_value:JEHOVAH'S WITNESS,RELIGION_value:JEWISH,RELIGION_value:MUSLIM,RELIGION_value:NOT SPECIFIED,RELIGION_value:OTHER,RELIGION_value:PROTESTANT QUAKER,RELIGION_value:UNITARIAN-UNIVERSALIST,RELIGION_value:UNOBTAINABLE
ID,,,,,,,,,,,,,,,,,,,,,
200001,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,61.111770,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
200010,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,27.271125,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
200016,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,67.281277,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
200033,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,67.191089,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
200034,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,54.077903,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
201110,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,54.746702,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
201113,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,50.456861,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
201124,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,70.488207,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
201125,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,79.555041,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
201128,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,74.814954,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

                   DiaBP_mask  HR_mask  RR_mask  SpO2_mask  SysBP_mask  \
ID     t_range
200001 [0.0, 1.0)         1.0      1.0      1.0        1.0         1.0
       [1.0, 2.0)         1.0      1.0      1.0        1.0         1.0
       [2.0, 3.0)         1.0      1.0      1.0        1.0         1.0
       [3.0, 4.0)         1.0      1.0      1.0        1.0         1.0
200010 [0.0, 1.0)         0.0      0.0      0.0        0.0         0.0
...                       ...      ...      ...        ...         ...
201125 [3.0, 4.0)         1.0      1.0      1.0        1.0         1.0
201128 [0.0, 1.0)         0.0      0.0      0.0        0.0         0.0
       [1.0, 2.0)         1.0      1.0      1.0        0.0         1.0
       [2.0, 3.0)         1.0      1.0      1.0        0.0         1.0
       [3.0, 4.0)         1.0      1.0      1.0        0.0         1.0

                   220046_value  220047_value  220048_value  \
ID     t_range
200001 [0.0, 1.0)    120.000000     60.000000           1.0
       [1.0, 2.0)    120.940594     53.935961           1.0
       [2.0, 3.0)    120.940594     53.935961           1.0
       [3.0, 4.0)    120.940594     53.935961           1.0
200010 [0.0, 1.0)    120.000000     50.000000           1.0
...                         ...           ...           ...
201125 [3.0, 4.0)    130.000000     60.000000           1.0
201128 [0.0, 1.0)    120.940594     53.935961           1.0
       [1.0, 2.0)    120.000000     50.000000           1.0
       [2.0, 3.0)    120.940594     53.935961           1.0
       [3.0, 4.0)    120.940594     53.935961           1.0

                   220048: 1st AV (First degree AV Block) _value  \
ID     t_range
200001 [0.0, 1.0)                                            1.0
       [1.0, 2.0)                                            1.0
       [2.0, 3.0)                                            1.0
       [3.0, 4.0)                                            1.0
200010 [0.0, 1.0)                                            1.0
...                                                          ...
201125 [3.0, 4.0)                                            1.0
201128 [0.0, 1.0)                                            1.0
       [1.0, 2.0)                                            1.0
       [2.0, 3.0)                                            1.0
       [3.0, 4.0)                                            1.0

                   220048: 3rd AV (Complete Heart Block) _value  ...  \
ID     t_range                                                   ...
200001 [0.0, 1.0)                                           1.0  ...
       [1.0, 2.0)                                           1.0  ...
       [2.0, 3.0)                                           1.0  ...
       [3.0, 4.0)                                           1.0  ...
200010 [0.0, 1.0)                                           1.0  ...
...                                                         ...  ...
201125 [3.0, 4.0)                                           1.0  ...
201128 [0.0, 1.0)                                           1.0  ...
       [1.0, 2.0)                                           1.0  ...
       [2.0, 3.0)                                           1.0  ...
       [3.0, 4.0)                                           1.0  ...

                   51492_value_str:NEG  51492_value_str:TR  \
ID     t_range
200001 [0.0, 1.0)                  0.0                 0.0
       [1.0, 2.0)                  0.0                 0.0
       [2.0, 3.0)                  0.0                 0.0
       [3.0, 4.0)                  0.0                 0.0
200010 [0.0, 1.0)                  0.0                 0.0
...                                ...                 ...
201125 [3.0, 4.0)                  0.0                 0.0
201128 [0.0, 1.0)                  0.0                 0.0
       [1.0, 2.0)                  0.0                 0.0
       [2.0, 3.0)                  0.0                 0.0
       [3.0, 4.0)                  0.0                 0.0

                   51493_value_str:0-2  51493_value_str:>50  \
ID     t_range
200001 [0.0, 1.0)                  0.0                  0.0
       [1.0, 2.0)                  0.0                  0.0
       [2.0, 3.0)                  0.0                  0.0
       [3.0, 4.0)                  0.0                  0.0
200010 [0.0, 1.0)                  0.0                  0.0
...                                ...                  ...
201125 [3.0, 4.0)                  1.0                  0.0
201128 [0.0, 1.0)                  0.0                  0.0
       [1.0, 2.0)                  0.0                  0.0
       [2.0, 3.0)                  0.0                  0.0
       [3.0, 4.0)                  0.0                  0.0

                   51498_value_str:>=1.035  51514_value_str:NEG  \
ID     t_range
200001 [0.0, 1.0)                      0.0                  0.0
       [1.0, 2.0)                      0.0                  0.0
       [2.0, 3.0)                      0.0                  0.0
       [3.0, 4.0)                      0.0                  0.0
200010 [0.0, 1.0)                      0.0                  0.0
...                                    ...                  ...
201125 [3.0, 4.0)                      0.0                  1.0
201128 [0.0, 1.0)                      0.0                  0.0
       [1.0, 2.0)                      0.0                  0.0
       [2.0, 3.0)                      0.0                  0.0
       [3.0, 4.0)                      0.0                  0.0

                   51516_value_str:0-2  51516_value_str:3-5  \
ID     t_range
200001 [0.0, 1.0)                  0.0                  0.0
       [1.0, 2.0)                  0.0                  0.0
       [2.0, 3.0)                  0.0                  0.0
       [3.0, 4.0)                  0.0                  0.0
200010 [0.0, 1.0)                  0.0                  0.0
...                                ...                  ...
201125 [3.0, 4.0)                  0.0                  1.0
201128 [0.0, 1.0)                  0.0                  0.0
       [1.0, 2.0)                  0.0                  0.0
       [2.0, 3.0)                  0.0                  0.0
       [3.0, 4.0)                  0.0                  0.0

                   51516_value_str:6-10  51516_value_str:>50
ID     t_range
200001 [0.0, 1.0)                   0.0                  0.0
       [1.0, 2.0)                   0.0                  0.0
       [2.0, 3.0)                   0.0                  0.0
       [3.0, 4.0)                   0.0                  0.0
200010 [0.0, 1.0)                   0.0                  0.0
...                                 ...                  ...
201125 [3.0, 4.0)                   0.0                  0.0
201128 [0.0, 1.0)                   0.0                  0.0
       [1.0, 2.0)                   0.0                  0.0
       [2.0, 3.0)                   0.0                  0.0
       [3.0, 4.0)                   0.0                  0.0

[800 rows x 2588 columns]