In [ ]:
eicu_path = '/scratch/wiensj_root/wiensj/shared_data/datasets/eicu-2.0/' #read from here
save_path = '/scratch/wiensj_root/wiensj/shared_data/FIDDLE_project/extracted/' #save here

import pandas as pd
import numpy as np
from tqdm import tqdm

In [ ]:
# read in the file
fname = 'patient'
df = pd.read_csv(eicu_path + fname + '.csv')
df = df[['patientunitstayid', 'gender', 'age', 'ethnicity', 'hospitalid', 'wardid', \
         'apacheadmissiondx', 'admissionheight', 'hospitaladmittime24', \
         'hospitaladmitoffset', 'hospitaladmitsource', 'unittype', \
         'unitadmittime24','unitadmitsource', 'unitvisitnumber', \
         'unitstaytype', 'admissionweight', 'uniquepid']]
df = df.iloc[:,0:].set_index(['patientunitstayid']) #, 'observationoffset'

df.columns.name = 'variable_name'

df = df.stack()

df.name = 'variable_value'
df = df.reset_index()
df = pd.DataFrame(df)
df['t'] = np.nan
df = df[['patientunitstayid','t', 'variable_name', 'variable_value']]

In [3]:
# read in the file
fname = 'lab'
df = pd.read_csv(eicu_path + fname + '.csv')

# select relevant columns
df = df[['patientunitstayid', 'labresultoffset', 'labname', 'labothervaluetext']]
df['labresulttext'] = pd.to_numeric(df['labresulttext'], errors='ignore') #for lab and costum lab

# rename the columns
df = df.rename(columns={
    'patientunitstayid': 'ID', 
    'labresultoffset': 't', 
    'labname': 'variable_name', 
    'labresulttext': 'variable_value',
})

# save the file
#df.to_parquet(data_path + fname + '.parquet', index=False)

In [ ]:
# select relevant columns
df = df[['patientunitstayid', 'pasthistoryoffset', 'pasthistorypath']]

# rename the columns
df = df.rename(columns={
    'patientunitstayid': 'ID', 
    'pasthistoryoffset': 't', 
    'pasthistorypath': 'variable_name', 
})

df['variable_value'] = 1

# save the file
df.to_parquet(data_path + fname + '.parquet', index=False)

In [5]:
#use this if columns are of mixed types
import pickle

with open(data_path + fname + '.pickle', 'wb') as f:
    pickle.dump(df, f, protocol=pickle.HIGHEST_PROTOCOL)

In [4]:
df

               ID     t       variable_name variable_value
0          141168  2026          fibrinogen            177
1          141168  1133            PT - INR            2.5
2          141168  2026           magnesium            2.0
3          141168  1133                  PT           26.6
4          141168  2141                  pH           7.20
5          141168   231            PT - INR            1.7
6          141168  1701  urinary creatinine         173.12
7          141168  2026                 MCH           29.2
8          141168   516                 BUN             26
9          141168  1701      urinary sodium             12
10         141168  2141                HCO3             14
11         141168   231                  PT           17.1
12         141168  2026             lactate           12.2
13         141168  2026                 BUN             29
14         141168  2026                 CPK            216
15         141168   231                 PTT             29
16         141168  2141                FiO2           100%
17         141168   516             -lymphs             19
18         141168  2026        Base Deficit             17
19         141168  2026                 BNP            623
20         141168  1133            chloride            101
21         141168  1136           uric acid            8.1
22         141168  2141        Base Deficit             13
23         141168  2026        troponin - I           0.26
24         141168  2026                paO2             68
25         141168  2026                -eos              0
26         141168  1805                HCO3             15
27         141168  2026                HCO3             11
28         141168  2141                paO2            121
29         141168  1133    platelets x 1000            213
...           ...   ...                 ...            ...
39132501  3353263    -7              CPK-MB            1.1
39132502  3353263  2650                 PTT             53
39132503  3353263    -7                 MPV            7.2
39132504  3353263    -7                 CPK            133
39132505  3353263  1733                 PTT             50
39132506  3353263    -7        CPK-MB INDEX            0.8
39132507  3353263    -7    platelets x 1000            161
39132508  3353263  6919                 PTT             51
39132509  3353263  7490          WBC x 1000            4.5
39132510  3353263  1109                 PTT             60
39132511  3353263    -7                 MCH             27
39132512  3353263  6446                 PTT             87
39132513  3353263  1733                 MPV            7.2
39132514  3353263    -7                 Hgb           14.9
39132515  3353263  7490                 MPV            7.0
39132516  3353263    -7    platelets x 1000            164
39132517  3353263  1733                 MCV             82
39132518  3353263    -7                MCHC             33
39132519  3353263  1733    platelets x 1000            169
39132520  3353263   -37                 PTT             25
39132521  3353263  1733                MCHC             34
39132522  3353263    -7                 MCH             27
39132523  3353263  1733                 Hct             38
39132524  3353263    -7                 RDW           13.3
39132525  3353263  1733                 Hgb           12.9
39132526  3353263    -7          WBC x 1000            6.4
39132527  3353263  1733                 RBC           4.67
39132528  3353263    -7              -monos             10
39132529  3353263  1733          WBC x 1000            6.6
39132530  3353263  1733                 MCH             28

[39132531 rows x 4 columns]